version: '2'
services:
  app:
    container_name: docker-node-postgreSQL
    restart: always
    build: .
    ports:
      - '80:3000'
    links: 
      - postgres

  postgres:
    container_name: docker-postgres
    image: postgres
    ports: 
      - '5432:5432'